server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #路由id,可以任意
        - id: user-service
          #代理的服务地址
          #uri: http://127.0.0.1:9091
          #lb 表示从eureka中获取服务
          uri: lb://user-service
          #路由断言 可以匹配映射路径
          predicates:
            - Path=/a/b/user/**
          filters:
            #添加请求路径的前缀
            #- PrefixPath=/user
            #2表示过滤2个路径
            - StripPrefix=2
            - MyParam=name
      default-filters:
        # 默认过滤器,对所有路由都生效      
        - AddResponseHeader=X-Response-Default-MyName, itcast
        - AddResponseHeader=aa, bb
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: * # 这种写法或者下面的都可以，*表示全部
            allowedOrigins:
            - "http://docs.spring.io"
            allowedMethods:
            - GET
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

